import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import { Header } from "../components/shared/Header";
import { Footer } from "../components/shared/Footer";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import "app/sass/globals.sass";
config.autoAddCss = false

const notoSans = Noto_Sans({
  subsets: ["latin-ext"],
  display: "swap",
  weight: ["400", "700"],
})

export const metadata: Metadata = {
  title: "Dormi Luna",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={notoSans.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
